from __future__ import annotations

import sys
from pathlib import Path as _Path

sys.path.insert(0, str(_Path(__file__).resolve().parents[1]))

import argparse
import json
from pathlib import Path
from statistics import mean

from app.experiments import calibration_lab, genomic_ablation
from app.population import monte_carlo_policy
from app.validation import bootstrap_mean_ci
from app.world import simulate_world

OUT = Path("results")


def main() -> None:
    parser = argparse.ArgumentParser(description="Scientific validation suite for the synthetic Digital Twin")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--seeds", type=int, default=8)
    parser.add_argument("--learners", type=int, default=32)
    parser.add_argument("--years", type=int, default=8)
    args = parser.parse_args()

    seeds = [args.seed + i * 1009 for i in range(args.seeds)]
    world_competency = []
    world_wellbeing = []
    genome_deltas = []
    calibration: dict[str, list[dict]] = {}

    for seed in seeds:
        world = simulate_world(seed, learners=args.learners, years=args.years, policy_name="digital_twin", return_trajectories=False)
        world_competency.append(world["metrics"]["competency_mean"])
        world_wellbeing.append(world["metrics"]["wellbeing_mean"])

        genome = genomic_ablation(seed, size=16)
        genome_deltas.append(genome["mean_effect_of_genomic_prior"]["pathway_stability"])

        for scenario in ("traditional", "adaptive", "genomic_adaptive", "global_digital_twin"):
            calibration.setdefault(scenario, []).append(calibration_lab(seed, size=16, scenario=scenario))

    convergence = {
        "repetitions": {
            str(n): monte_carlo_policy(args.seed, policy="digital_twin", repetitions=n, learners=16, years=4)["metrics"]["competency_mean"]
            for n in (4, 8, 16)
        }
    }
    calibration_summary = {}
    for scenario, rows in calibration.items():
        raw_brier = [row["raw"]["brier_multiclass"] for row in rows]
        calibrated_brier = [row["calibrated"]["brier_multiclass"] for row in rows]
        raw_ece = [row["raw"]["ece_top_class"] for row in rows]
        calibrated_ece = [row["calibrated"]["ece_top_class"] for row in rows]
        calibration_summary[scenario] = {
            "seeds": len(rows),
            "raw_brier_ci95": bootstrap_mean_ci(raw_brier, seed=args.seed + 1),
            "calibrated_brier_ci95": bootstrap_mean_ci(calibrated_brier, seed=args.seed + 2),
            "raw_ece_ci95": bootstrap_mean_ci(raw_ece, seed=args.seed + 3),
            "calibrated_ece_ci95": bootstrap_mean_ci(calibrated_ece, seed=args.seed + 4),
            "mean_temperature": round(mean(row["temperature"] for row in rows), 6),
        }

    result = {
        "schema_version": "validation-1.0",
        "seed": args.seed,
        "seed_count": args.seeds,
        "world": {
            "competency_mean_ci95": bootstrap_mean_ci(world_competency, seed=args.seed + 10),
            "wellbeing_mean_ci95": bootstrap_mean_ci(world_wellbeing, seed=args.seed + 11),
        },
        "genomic_ablation": {
            "paired_pathway_stability_delta_ci95": bootstrap_mean_ci(genome_deltas, seed=args.seed + 12),
            "interpretation": "Synthetic architectural ablation; not evidence for real genetic utility.",
        },
        "monte_carlo_convergence": convergence,
        "calibration_across_seeds_and_policies": calibration_summary,
        "limitations": [
            "All validation data are generated by the simulator.",
            "Confidence intervals quantify simulator variability, not uncertainty in a real population.",
            "Calibration is evaluated against the simulator's next-year pathway persistence target.",
        ],
    }
    OUT.mkdir(exist_ok=True)
    path = OUT / "scientific_validation.json"
    path.write_text(json.dumps(result, indent=2), encoding="utf-8")
    print(json.dumps({"output": str(path), "seed_count": args.seeds}, indent=2))


if __name__ == "__main__":
    main()
